In [1]:
import pandas as pd
from konlpy.tag import Okt
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer

In [2]:
df = pd.read_csv('./data/전처리_샘플뉴스.csv')
df

,title,text,url,media,date
0,방역 2.5단계 뒤 을씨년스럽게 변한 '스벅'···별천지된 '파바',서울의 밤이 달라졌다. 수도권을 대상으로 이른바 ‘사회적 거리두기 2.5단계’가 시...,https://news.naver.com/main/read.nhn?mode=LPOD...,중앙일보,2020-08-31
1,"""기적 같은 선방""이라지만...현장은 성한 곳이 없다","“50년 동안 사업하면서 소위 ‘깡통’을 세 번 차고도 재기했는데, 이번 위기는 정...",https://news.naver.com/main/read.nhn?mode=LPOD...,한국일보,2020-08-03
2,13일까지 장맛비… 사흘간 물폭탄 사망·실종 25명,곳곳 수해 초비상 \r\n\r\n 3일 오전 충남 천안과 아산지역에 호우경보가...,https://news.naver.com/main/read.nhn?mode=LPOD...,세계일보,2020-08-04
3,최악 장마에 태풍까지… 내일까지 최고 300㎜,예측하기 어려운 ‘물폭탄’을 동반한 장마가 유례없이 길어지고 있다. 설상가상으로 9...,https://news.naver.com/main/read.nhn?mode=LPOD...,국민일보,2020-08-10
4,은행 예금금리 사상 첫 0%대,대출금리도 2.72% 사상최저\r\n\r\n\r\n\r\n\t\t\t\t은행 예금에...,https://news.naver.com/main/read.nhn?mode=LPOD...,조선일보,2020-08-01

In [4]:
txt_res = []
for i in df['text']:
    txt_res.extend(i.split('\n'))
txt_res

['서울의 밤이 달라졌다. 수도권을 대상으로 이른바 ‘사회적 거리두기 2.5단계’가 시행되면서 음식점 등이 오후 9시에 대거 문을 닫았기 때문이다.  \r',
 ' \r',
 '   2.5단계 시행 첫날인 이날 서울 중심가의 식당과 술집 등은 매장 내 취식 금지 시작 시각인 오후 9시를 전후로 속속 장사를 접었다. 한식집 등 식사 위주의 식당은 해가 지면서 일찌감치 마감했고, 고깃집이나 횟집·이자카야·맥줏집 등도 ‘데드라인’이 임박하자 손님을 내보내고 매장을 정리하기 시작했다. 평소라면 간판 불빛으로 불야성이었을 번화가 골목들이 깜깜해질 정도였다.  \r',
 ' \r',
 '   서울 종각역 인근 맥줏집 사장 김모(30)씨는 오후 8시50분이 되자 손님들에게 “오후 9시 마감이니 나가 달라”고 부탁했다. 이 가게의 평소 영업시간은 오후 5시부터 다음 날 오전 2시까지였다. 김씨는 “원래 가장 붐비는 시간인데 문을 닫아야 한다. 코로나19 때문에 매출액이 예년의 4분의 1로 줄었는데 이젠 그 반토막도 안 될 것 같다”고 한숨을 내쉬었다.  \r',
 ' \r',
 '              오후 9시쯤 한 식당에서 나온 최모(22)씨는 “친구들과의 약속 때문에 나왔는데 강제로 이 시간에 귀가해야 한다니 아쉽다”고 말했다. 4층 규모의 한 대형 술집은 ‘2.5단계’가 시행되는 다음 달 6일까지 아예 문을 닫기로 했다. 이 술집 사장은 “오후 9시까지만 영업하라는 건 그냥 술집 문을 닫으라는 이야기”라며 “포장, 배달은 가능하다지만 누가 술집에서 술이나 안주를 배달시켜 먹겠나”라고 말했다. 서울역 대합실 내 한식당 등도 오후 9시 이전에 문을 닫았다. 패스트푸드 가게도 일부 포장 주문 손님만 눈에 보일 뿐 한산했다.  \r',
 ' \r',
 '   서울 중구의 한 순댓국집 사장 홍정복(60)씨는 “원래 오후 9시에서 오전 1시 사이의 매출이 전체의 30%를 차지한다”며 “매출액이 줄어 아쉽지만, 많이들 동참해 최대한 빨리 코로나19가 잠잠해지길 바란다”고 말했다.  \r',
 ' \r',
 '   업종별로 희비가 갈리기도 했다. 온종일 포장·배달 판매만 가능한 프랜차이즈 커피전문점은 썰렁한 모습이었다.  \r',
 ' \r',
 ' 결혼식 온라인 생중계, 축하는 댓글로 축의금은 계좌이체  \r',
 ' \r',
 '              30일 오후 1시 ‘정자동 카페거리’로 불리는 경기도 성남시 분당구 정자동 카페 밀집지역의 스타벅스에서는 고객을 찾아보기 어려웠다. 어쩌다 찾은 고객도 발길을 돌리기 일쑤였다. 매장 직원은 “포장 판매만 가능하다는 설명을 듣고 발길을 돌린 고객이 10명 이상이다. 화를 낸 고객도 있었다”며 한숨을 내쉬었다.  \r',
 ' \r',
 '   하지만 이곳에서 불과 180m 떨어진 파리바게뜨는 별천지였다. 4인석 테이블 10개 중 8개에 손님이 앉아 있었다. 이들은 가족·지인과 모여 앉아 커피를 마시거나 빵을 먹었다. 노트북 컴퓨터를 이용해 개인업무를 보는 이도 있었다. 제과점은 음식점과 마찬가지로 오전 5시부터 오후 9시까지는 현장 취식이 가능하기 때문이다. 또 다른 ‘무풍지대’인 비(非)프랜차이즈형 소규모 개인카페도 고객으로 북적였다. 소셜네트워크서비스(SNS)에서 인기를 끌고 있는 경기도 광주시의 한 카페는 낮 12시에 이미 12대를 수용할 수 있는 1층 주차장이 만차 상태였다.  \r',
 ' \r',
 '   프랜차이즈 커피전문점 중에서도 차 안에서 음료를 받는 드라이브 스루(Drive-thru) 방식의 매장은 현장 취식 금지 대상이 아니라 고객 발길이 이어졌다. 낮 12시30분쯤 경기도 남양주시의 한 스타벅스 드라이브 스루 점포로 들어서는 차로에는 차량 14대가 줄줄이 늘어서 있었다. 송파나루역 인근 매장에서도 고객이 몰리면서 차량이 70~80m나 줄을 서는 바람에 교통체증이 빚어졌다. 한 프렌차이즈 커피전문점 관계자는 “똑같이 빵과 커피를 파는데 우리는 안 되고, 제과점은 된다는 게 말이 되느냐”고 불만을 토로하기도 했다.  \r',
 ' \r',
 '   방역 강화로 50명 이상 규모의 현장 결혼식이 원천 봉쇄되면서 ‘온라인 결혼식’으로 방향을 선회한 부부도 늘고 있다. 예식을 한 차례 연기했던 신준하(37)·김지현(33) 부부는 최근 코로나19가 재확산하자 ‘오프라인 결혼식’을 포기하고 온라인 결혼식을 올렸다. 이들은 모바일 청첩장에 결혼식 영상 중계 홈페이지 주소를 첨부해 지인들에게 보냈다.  \r',
 ' \r',
 '   29일 오후 2시30분부터 생중계된 이들의 결혼식을 90명에 가까운 ‘온라인 하객’이 지켜봤다. 신부 아버지가 직접 축가를 하자 “아버님의 축가가 너무 멋지네요”라는 댓글이 달리기도 했다. 신씨는 “이번 사태를 계기로 결혼식 문화가 바뀔 수 있겠다는 생각도 든다”고 말했다. 22일 대만 여성과 한국에서 결혼식을 올린 김모(33)씨도 온라인 생중계를 했다. 코로나19 재확산으로 대만에 있는 신부 부모가 참석하지 못했기 때문이다.  \r',
 ' \r',
 '   온라인 결혼식 중계를 하는 이준희 가빈컴퍼니 대표는 “‘온라인 하객’은 계좌번호를 링크 형태로 전달받아 축의금을 보낼 수 있고, 혼주 쪽에서는 하객이 입력한 주소와 전화번호를 이용해 답례품을 보낼 수 있다”며 “지난 18일 하객 수 제한 조처 이후 300건이 넘는 문의가 쏟아졌다”고 말했다. 한편 질병관리본부 중앙방역대책본부(방대본)에 따르면 30일 0시 기준 전국의 코로나19 환자는 하루 동안 299명 늘어 지난 25일(280명) 이후 닷새 만에 300명 아래로 떨어졌다. 정은경 방대본부장은 “코로나19가 최후의 방어선이라 생각한 의료기관과 요양시설로까지 확산 중이며 역학조사 여력도 한계에 다다른 상황”이라며 “코로나19를 다시 통제 가능한 수준으로 줄일 수 있을지 판가름할 중요한 시기인 만큼 거리두기를 철저히 이행해 달라”고 말했다.  \r',
 ' \r',
 '   정진호·채혜선·권혜림·백민정 기자 jeong.jinho@joongang.co.kr  \r',
 '\r',
 '\r',
 '▶ \r',
 '▶ \r',
 '▶ \r',
 '\r',
 'ⓒ중앙일보(https://joongang.co.kr), 무단 전재 및 재배포 금지',
 '“50년 동안 사업하면서 소위 ‘깡통’을 세 번 차고도 재기했는데, 이번 위기는 정말 심각하네요. 빚으로 버티는 주변 기업들을 보면, 근근이 입에 풀칠이라도 하는 게 다행인가 싶어요.”\r',
 '\r',
 '지난달 30일 인천에서 만난 양변기·세면대 부속품 제조업체 대표인 A씨의 낮은 목소리에선 기운을 찾아보긴 어려웠다. 그도 그럴 것이 요즘 공장 가동률은 평년의 절반에도 못 미치는 데다, 생산직 근로자들은 수개월째 주4일만 나오고 있다. 1979년 석유파동에서부터 1998년 외환위기와 2008년 금융위기 등 3번의 위기 속에서도 매번 오뚝이처럼 일어섰지만 이번 만큼은 절망적이란 게 그의 푸념섞인 한탄이다. 산전수전을 모두 겪어온 A대표도 도무지 신종 코로나바이러스 감염증(코로나19) 여파를 뚫고 나갈 재간이 없다고 했다. 주문량이 3분의 1로 줄어든 협력업체 대표들이 돈 빌리러 다니는 걸 보며 A씨는 “기업들이 빚으로 하루하루 버티고 있다는 게 실감 난다”고 씁쓸해했다.\r',
 '\r',
 '산업현장이 코로나19 장기화 여파에 줄초상 위기로 빠져들고 있다. 중소기업뿐 아니라 외식 면세 여행 항공 자동차 등 실물경제에 활력을 불어넣던 산업들이 코로나19의 긴 터널에서 헤어나오지 못하는 모습이다. 산업현장은 성한 곳이 없는데, 청와대에선 현실과는 동떨어진 ‘경제선방론’을 들고 나오면서 원성만 높아지고 있다. 문재인 대통령은 지난달 27일 2분기 우리 경제에 대해 “기적 같은 선방이었다”고 평가했지만 기업과 상인들은 “앉아서 숫자만 보는 사람들이 뭘 알겠느냐”며 분통을 터뜨리고 있다.\r',
 '\r',
 '"악으로 버티고 있는데..."\r',
 '\r',
 '최근 청와대와 정부는 코로나19에도 불구하고 우리 경제가 상반기에 선방했고, 하반기에는 나아질 것이란 낙관적 전망을 잇따라 내놓았다. 몇몇 수치만 보면 아예 빗나간 분석은 아니다. 올해 우리나라 2분기 경제성장률은 1분기 대비 -3.3%를 기록했다. 경제협력개발기구(OECD) 국가들의 성장 후퇴 폭보다 작다. 산업통상자원부에 따르면 월별 수출은 4~6월 연속 작년 동기 대비 두 자릿수 감소세를 이어가다 7월 들어 한 자릿수로 감소 폭이 줄었다. 현재 경기 상황을 보여주는 통계청의 경기동행지수 순환변동치는 4개월 연속 내리막길을 걸은 이후 6월 반등했다.\r',
 '\r',
 '하지만 -3.3%는 과거 금융위기(2008년 4분기) 때의 -3.28%보다 낮은 성장률이다. 수출은 감소율이 둔화했을 뿐 여전히 마이너스다. 반짝 반등한 경기지수는 하반기 코로나19 상황에 따라 언제 다시 곤두박질칠 지 장담할 수 없다. 무엇보다 중요한 건 산업현장의 체감 경기다. 각종 지수에 드러나지 않는 실물경제의 어려움을 외면한 청와대와 정부의 장밋빛 전망에 기업과 상인들 사이에선 “현실을 몰라도 너무 모른다”며 “솔직히 청와대가 좋은 수치만 보고 말하는 것 아니냐”고 볼멘소리가 나온다.\r',
 '\r',
 '현주소는 외식업계에서부터 확인된다. 서울 중구 명동에서 외식매장을 운영하는 B씨는 7월 매출 집계를 앞두고 걱정부터 앞선다고 했다. 몇 달째 매출이 전년의 30~40% 수준을 벗어나지 못하고 있어서다. 브레이크 타임(오후 3~5시)까지 만들어 인건비를 줄였지만 직원들은 무급휴직을 보내야 했다. B씨는 “유통업계에 15년째 몸담고 있는데, 이렇게 어려운 상황은 처음이다”라고 토로했다.\r',
 '\r',
 '외식업계의 고통지수는 통계에서도 드러난다. 한국외식산업연구원이 지난 4월 외식업체 600곳을 대상으로 조사한 결과 응답 업체의 80.8%에서 고객 수가 감소했다. 35.2%는 직원 수를 줄였다. 상반기 서울에서만 식품위생업소 4,219곳이 문을 닫았다. 한 외식업체 관계자는 “요즘 외식 브랜드 매장들은 음악 소리까지 줄여가며 고객 모으기에 안간힘”이라고 전했다. 음악이 크면 말이 들리지 않아 서로 가까이 가게 되니 고객들이 매장을 외면할까 걱정해서다. 이 관계자는 “오죽하면 이런 것마저 조심하겠나”라며 “악으로 버티고 있는데 경제 선방이 웬 말인지 모르겠다”고 답답해했다.\r',
 '\r',
 '지난 5월 긴급재난지원금이 지급된 뒤 잠시 활기를 찾았던 소상공인들의 표정도 다시 굳어지고 있다. 지급 한 달째를 넘은 6월부터 손님 발길이 눈에 띄게 줄었기 때문이다. 소상공인시장진흥공단의 경기동향조사에 따르면 6월 전통시장의 체감경기지수(BSI)는 79.2로, 전 달보다 30.0포인트 급락했다. 코로나19 재확산 우려가 커진 데다 재난지원금 효과가 소진됐기 때문으로 풀이된다.\r',
 '\r',
 '\r',
 '\r',
 '\r',
 '\r',
 '하반기는 또 다른 긴 터널 \r',
 '\r',
 '지쳐가는 건 면세점 업계도 마찬가지다. 업계에선 “올해 장사는 끝난 것 같다”며 하반기 기대마저 접는 분위기다. 한 면세점 판매직원은 “마이너스 매출에 문을 열어도 온종일 손님이 한 명도 없는 날이 적지 않다”고 전했다. 지난 4월 국내 면세점 매출은 1조원선이 무너졌다. 6월 매출도 작년 같은 달과 비교하면 43%나 떨어졌다. 면세점 매출의 80%는 외국인에게서 나오는데, 하늘길이 막혀 있는 한 경영 정상화는 먼 얘기다. 업계 관계자는 “따이공(代工·중국 보따리상)이 조금씩 늘고 있기는 하지만, 입국 후 14일간 자가격리해도 남는 장사라고 판단하는 일부 대형 보따리상 위주라 매출 회복은 내년에도 기약하기 힘들다”고 하소연했다.\r',
 '\r',
 '‘언제 다시 비행할 수 있을까’ 하고 막연히 기다렸던 항공업계 역시 한숨만 늘어가는 분위기다. 이스타항공 승무원 C씨는 회사 인수합병(M&A)만 마무리되면 다시 일할 수 있을 거란 희망고문으로 상반기를 버텼다.  “3월 말부터 유니폼을 한 번도 입지 못했다”는 C씨는 “몇 달간 월급도 못 받았는데, 회사가 파산하고 일자리를 잃게 된다는 얘기가 들린다”며 불안해했다. 9월부터 정부의 고용유지지원금이 중단되면 항공업계 근무자 총 3만여명 중 절반 가량이 실직할 거라는 전망마저 나온다. 정부와 청와대가 경기 회복을 기대한다는 하반기가 이들에겐 또 다른 긴 터널의 시작인 셈이다.\r',
 '\r',
 '휴가철 국내 여행 수요가 늘면서 한편에선 관련 업계의 실적 회복을 점치는 눈치다. 하지만 현실은 냉혹하다. 여행사들 매출 중 국내 여행상품 비중은 3% 미만이고, 수익률은 1%에도 못 미친다. 한 여행사 관계자는 “우리나라는 대중교통이 잘 발달돼 있고 요금도 저렴해 여행상품 수요가 많지 않다”며 “국내 여행을 상품화하고는 있지만 수익을 기대하지는 못한다”고 말했다. 호텔업계 역시 하반기가 어둡다. 프리미엄 호텔 관계자는 “우리 호텔을 먹여 살리는 건 비즈니스 수요인데, 해외 입국이 막히고 내국인도 출장을 자제하면서 방 100개 중 90개가 비어 있다”고 전했다.\r',
 '\r',
 '\r',
 '\r',
 '"문 닫는 기업 속출할 지도"\r',
 '\r',
 '경제를 떠받쳐온 자동차 업체들도 여전히 허덕이고 있다. 현대·기아차는 상반기 2조원대 흑자를 기록했지만, 지난해 같은 기간보다 35.9% 감소한 수치다. 쌍용차는 14분기 연속 적자를 기록했다. 올 하반기에는 내수 -5%, 해외 -30% 이상 침체가 예상돼 연간 판매 700만대 붕괴도 우려된다. 불황 타개책인 신차 출시마저 코로나19 여파로 일정이 줄줄이 밀리고 있다.\r',
 '\r',
 '부품업체는 더 힘들다. 한국자동차산업연합회에 따르면 올해 국내 자동차부품 기업 평균 손실액이 176억원에 달할 것으로 예상된다. 수출 물량이 절반 가량 줄었고, 대금 수령이 늦어지면서 유동성 위기도 커졌다. 자동차 공조기와 전장부품을 생산하는 D업체는 9월까지 필요한 유동성 중 40%도 채 확보하지 못했는데, 은행에서 대출조차 안 된다. D업체 관계자는 “자금 조달이 너무 어렵다”며 “상반기엔 그나마 1분기에 벌어둔 돈으로 버텼지만, 하반기엔 코로나19 상황이 개선되지 않으면 문 닫는 기업들이 속출할 것”이라고 걱정했다.\r',
 '\r',
 '\r',
 '\r',
 '자동차 업계의 어려움은 이미 철강업계로 옮겨갔다. 포스코가 2분기에 사상 첫 분기 적자를 기록하자 협력업체들 사이에선 “굶어 죽게 생겼다”는 우려가 확산됐다. 포스코 철강제품을 가공해 건설사에 납품하는 협력업체 관계자는 “코로나19로 대기업 공장 건설이 중단돼 4만톤 이상의 철근과 형강이 갈 곳을 잃었다”며 “이런 상황이 더 지속되면 업계가 전멸할 수도 있을 것 같다”고 토로했다.\r',
 '\r',
 '산업계에선 정부가 일부 숫자에 근거해 낙관적 전망을 되풀이하기보다 코로나19와 미중 갈등 등 대내외 요인에 따른 불확실성을 최소화하며 피해 업계 지원을 지속해야 한다는 목소리가 커지고 있다. 김정식 연세대 경제학부 교수는 “코로나19는 세계가 함께 겪는 위기인 만큼 대외의존도가 높은 한국이 장기적으로 더 아플 수 있다”고 우려했다.\r',
 '\r',
 '임소형 기자 precare@hankookilbo.com\r',
 '윤태석 기자 sportic@hankookilbo.com\r',
 '류종은 기자 rje312@hankookilbo.com\r',
 '맹하경 기자 hkm07@hankookilbo.com\r',
 '\r',
 '\r',
 '\r',
 '▶ \r',
 '\r',
 '▶ \r',
 '\r',
 '▶',
 '곳곳 수해 초비상 \r',
 '\r',
 '    3일 오전 충남 천안과 아산지역에 호우경보가 발령된 가운데 이날 오후 아산시 온천대로 온양관광호텔 사거리 도로가 침수됐다. 독자 제공, 뉴시스    지난 1일부터 사흘 동안 내리 쏟아진 ‘물폭탄’으로 수도권 등 중부지방에서 인명·재산 피해가 속출했다. 오는 13일까지 중부지방에 비가 내릴 것으로 예보돼 각별한 주의가 요구된다.\r',
 ' \r',
 ' 3일 중앙재난안전대책본부(중대본)와 각 지방자치단체에 따르면 계속된 게릴라성 집중호우로 이날만 오후 8시 현재 경기 평택과 가평에서 3명씩 6명이 숨졌다. 실종 신고가 들어온 사람도 경기 포천(1명)과 가평(2명), 충남 아산(3명)에서 6명이 나왔다.\r',
 ' \r',
 ' 이날 오전 10시49분 평택시 청북읍 후사리 한 반도체 장비부품 제조공장에선 건물 뒤편 야산이 무너져 내리면서 가건물로 지어진 천막을 덮쳤다. 소방당국은 사고 후 1시간여 만인 낮 12시30분쯤 토사에 갇혀 있던 A(50)씨 등 근로자 4명을 구조해 인근 병원으로 옮겼지만 30대 근로자 3명은 끝내 숨졌다.\r',
 ' \r',
 ' 오전 10시37분 가평읍 산유리에선 산사태에 따른 토사가 펜션 사무동을 덮치면서 펜션 주인(여·65)과 딸(37), 손자(3), 직원 1명(40대 베트남인)이 매몰됐다. 오후 6시 현재 주인 일가족 3명의 시신이 수습됐다.\r',
 ' \r',
 ' 밭에 나갔다 급류에 휩쓸린 가평군 청평면 농민(75) 등 이날 실종자도 5명이나 돼 사망자는 더 늘 수 있다. 이로써 1∼3일 사흘간 중부지방을 강타한 집중호우에 따른 사망·실종자는 25명으로 늘었다.\r',
 '     3일 경기도 가평군 가평읍 산유리의 한 펜션에 토사가 덮쳐 소방당국이 중장비를 동원해 구조작업을 벌이고 있다. 뉴스1    경기·충북·강원에서 591가구 919명의 이재민이 발생했고 산사태와 하천·제방 범람, 주택 침수 등으로 일시 대피한 인원은 이 지역에서 1712명에 달했다. 시설물 피해로는 주택 356채와 비닐하우스 146동이 물에 잠겼다. 산사태는 126건, 하천·저수지 범람은 37건 발생해 도로와 교량 527건이 파손됐다. 농경지는 2329㏊ 침수됐다.\r',
 ' \r',
 ' 전국 20개 댐 중 충주댐과 대청댐 등 12곳이 밀려든 물을 감당하지 못해 방류하면서 경기 여주 청미천과 복하천, 남양주 왕숙천, 포천 영평천에는 홍수경보가 발령됐다.\r',
 ' \r',
 '  전날 오후 3시를 기해 위기단계를 최고 수준인 3단계(심각)로 격상한 중대본은 잇달아 집중호우 대처 및 피해 상황 긴급점검 회의를 열었다. 문재인 대통령은 이날 피해 상황을 보고받고 “인명 피해가 추가로 발생하지 않도록 정부와 지자체는 총력을 기울여주기 바란다”고 당부했다.\r',
 ' \r',
 '  기상청은 제4호 태풍 ‘하구핏’의 영향으로 5일까지 중부지방을 중심으로 비가 내릴 것으로 내다봤다. 3∼5일 예상 강수량은 서울·경기, 강원영서, 충청북부, 서해5도 지역이 100~300㎜(많은 곳은 500㎜ 이상), 강원영동, 충청남부, 경북북부 지역은 50∼100㎜(많은 곳 150㎜ 이상)다. 특히 서울과 경기도, 강원영서 지방은 13일까지 줄곧 비가 내릴 것으로 보인다.\r',
 ' \r',
 '  송민섭·남혜정·박현준 기자 stsong@segye.com\r',
 '\r',
 '\r',
 '\r',
 'ⓒ 세상을 보는 눈, 세계일보',
 '예측하기 어려운 ‘물폭탄’을 동반한 장마가 유례없이 길어지고 있다. 설상가상으로 9일부터 사흘간 전국에 최고 300㎜ 이상 많은 비가 쏟아질 전망이다. 올해 장마가 시작된 이후 벌써 50명에 달한 인명피해(사망·실종)가 더 늘어날까 우려되는 상황이다. 엎친 데 덮친 격으로 필리핀 동쪽 해상에서 생성된 제5호 태풍 ‘장미’가 북상하면서 10일부터 직접적인 영향권에 들어가게 되는 경남과 전남 남해안, 제주도에서 피해가 발생할 것으로 예상된다.\r',
 '\r',
 '기상청에 따르면 9일부터 11일까지 전국적으로 100~200㎜에 달하는 비가 내릴 것으로 예상된다. 기상청은 9일 “남북으로 폭이 좁고 동서로 긴 모양의 강수대가 형성돼 중부지방에 매우 강하고 많은 비가 내리겠다”며 “지역에 따른 강수량 편차도 클 것으로 보인다”고 설명했다. 일부 지역에서는 300㎜ 이상의 많은 비가 예상된다. 장마전선으로 비가 많이 내릴 것으로 보이는 곳은 서울과 경기 북부, 강원영서 북부 지역이다. 북한에도 지역에 따라 200㎜ 이상 비가 예상돼 경기도 북부지방 등 접경지대에서는 불어난 강물에 의한 피해를 입지 않도록 대비할 필요가 있다.\r',
 '\r',
 '\r',
 '10일부터는 태풍 ‘장미’가 한반도 남해안 일대에 상륙하면서 남부지방을 중심으로 많은 비가 예상된다. ‘장미’는 일본 오키나와 서쪽 해상을 통해 시속 37㎞ 속도로 북상해 10일 오후 부산 남서쪽 50㎞ 부근 해상에 상륙할 것으로 예상된다. 직접적인 영향권에 들게 되는 전남 남해안과 경남, 제주도, 지리산 부근에는 300㎜ 이상의 많은 비가 내릴 것으로 보인다.\r',
 '\r',
 '11일까지 장마전선과 태풍으로 인한 폭우와 강풍까지 예상되면서 인적·물적 피해 발생이 늘어날까 우려되고 있다. 중앙재난안전대책본부에 따르면 지난 6월 24일 중부지방에서 장마가 시작된 이후 집중호우로 39명이 사망했고, 11명은 실종됐다. 호우와 태풍으로 78명(사망·실종)의 인명 사고가 발생했던 2011년 이후 가장 많은 수치다. 지난 7일 호우가 집중된 전남 곡성군 오산면에선 산사태가 나 주택을 덮치면서 5명이 사망했고, 8일에도 전북 장수와 광주 북구, 전북 남원, 경남 거창, 전남 담양과 화순에서 산사태와 급류, 화재 등으로 8명이 숨졌다.\r',
 '\r',
 '산림청 산사태예방지원본부는 제주도를 제외한 전국 16개 시·도 81개 시·군·구에 산사태 예보(경보, 주의보)를 발령했다. 8월 들어 집중호우가 쏟아지면서 667건의 산사태가 일어났고, 전날인 8일에만 55건이 발생했다.\r',
 '\r',
 '정현수 오주환 기자 jukebox@kmib.co.kr\r',
 '\r',
 '\r',
 '\r',
 '\r',
 'GoodNews paper ⓒ , 무단전재 및 재배포금지',
 '대출금리도 2.72% 사상최저\r',
 '\r',
 '\r',
 '\r',
 '\t\t\t\t은행 예금에 사상 첫 \'0%대 금리\' 시대가 열렸다. 1억원을 은행에 예금해봤자 연간 100만원 받기도 어렵다는 얘기다. 은행 예·적금이 돈을 불리는 수단이 아닌, 있는 돈을 그저 안전하게 보관하는 \'금고\'에 그치는 시대가 된 셈이다. 이와 더불어 대출 금리는 역대 최저 기록을 갈아치웠다. "이러니 주식·부동산으로 돈이 안 쏠릴 수 없다"는 말이 나온다.\r',
 '\r',
 "한국은행이 31일 발표한 '6월 중 금융기관 가중평균금리'에 따르면, 지난달 은행 예금 금리는 0.88%로 전월 대비 0.19%포인트 내렸다. 역대 처음으로 '1%대' 금리가 깨진 것이다. 은행권의 정기예금 상품 67.1%는 금리 수준이 0%대였다. 코로나 사태 이후 한은이 기준금리를 사상 최저인 0.5%까지 끌어내리면서, 예금 금리 역시 덩달아 내려간 것이다.\r",
 '\r',
 '대출 금리도 일제히 역대 최저 수준으로 떨어졌다. 은행권의 대출 금리는 평균 2.72%로 역대 최저로 집계됐다. 가계 대출 금리는 2.67%였다. 신용대출(3.33→2.93%), 주택담보대출(2.52→2.49%) 모두 내렸다. 특히 신용대출 금리는 전월 대비 0.4%포인트나 떨어졌다. 신용대출 금리가 2%대로 내려온 건 이번이 처음이다.\r',
 '\r',
 '신용대출 금리가 유독 많이 떨어진 것은 정부가 주담대 규제를 강화하자 신용대출을 끌어다 집 사는 사람이 늘었기 때문이다.\r',
 '\r',
 '한은 관계자는 "6·17 부동산 대책을 전후로 주택 매매·전세 거래가 증가했는데, 주택 거래와 관련해 신용 대출을 받는 사람들은 우량 차주 비율이 큰 편"이라며 "신용등급이 높은 우량 차주 비율이 높아지자 전체 신용대출 금리가 떨어지는 현상이 나타났다"고 설명했다.\r',
 '\r',
 "시장금리가 떨어지면서 가계대출은 무서운 속도로 늘고 있다. 한은에 따르면 6월 은행 가계대출은 전월 대비 8조1000억원 증가한 928조9000억원에 달했다. 역대 6월 최대 증가 폭이다. 더 늦기 전에 집이나 주식을 사자는 '패닉 바잉' 수요가 가계대출 증가의 주범이라는 해석이 나온다. 워낙 금리가 낮기 때문에 너도나도 '빚투(빚내서 투자)'에 나선다는 얘기다.\r",
 '\r',
 "빚내서 주식에 투자하는 신용거래융자 잔액은 지난 30일 14조2120억원까지 치솟으며 사상 최고 기록을 경신했다. 지난해 평균(9조6788억원)보다 1.5배 규모다. '증시 대기 자금'으로 불리는 투자자 예탁금도 30일 기준 47조6458억원에 달했다. 지난 2018~2019년 평균 예탁금(25조~26조원)에 비하면 2배 가까이 불어난 셈이다.\r",
 '\r',
 '[이기훈 기자 mong@chosun.com]\r',
 '\r',
 '\r',
 '\r',
 ' \r',
 '\t\t▶  \r',
 '\t\t▶  \r',
 '\t\t▶ \r',
 '\r',
 '\t- Copyrights ⓒ 조선일보 & chosun.com, 무단 전재 및 재배포 금지 -']

In [5]:
np.shape(txt_res)

(159,)

In [6]:
okt = Okt()
nouns = [okt.nouns(i) for i in txt_res]

In [7]:
nouns[0]

['서울',
 '밤',
 '수도권',
 '대상',
 '사회',
 '거리',
 '두기',
 '단계',
 '시행',
 '음식점',
 '등',
 '오후',
 '대거',
 '문',
 '때문']

In [8]:
stopword = ['서울', '밤', '사회']
last_nouns = []
for noun in nouns:
    last_nouns.append([w for w in noun if w not in stopword])

In [9]:
last_nouns[0]

['수도권', '대상', '거리', '두기', '단계', '시행', '음식점', '등', '오후', '대거', '문', '때문']

In [10]:
len(last_nouns)

159

In [11]:
last_nouns = [i for i in last_nouns if len(i)!=0]

In [12]:
len(last_nouns)

66

In [13]:
txt = [' '.join(i) for i in last_nouns]
txt[0]

'수도권 대상 거리 두기 단계 시행 음식점 등 오후 대거 문 때문'

## TF (문서에서 단어가 언급된 횟수)

In [15]:
word_list = sorted(list(set([n for nouns in last_nouns for n in nouns])))
word_list

['가건물',
 '가게',
 '가계',
 '가공',
 '가구',
 '가까이',
 '가동',
 '가량',
 '가빈',
 '가운데',
 '가의',
 '가장',
 '가족',
 '가중',
 '가평',
 '가평군',
 '가평읍',
 '각',
 '각별',
 '각종',
 '간판',
 '갈등',
 '갈리',
 '감당',
 '감소',
 '감염증',
 '감치',
 '강물',
 '강수',
 '강수량',
 '강원',
 '강원영동',
 '강제',
 '강타',
 '강풍',
 '강화',
 '개',
 '개선',
 '개월',
 '개인',
 '거',
 '거란',
 '거래',
 '거리',
 '거창',
 '걱정',
 '건',
 '건물',
 '건설',
 '건의',
 '걸',
 '것',
 '게',
 '게릴라',
 '격',
 '격리',
 '격상',
 '결과',
 '결혼식',
 '경',
 '경기',
 '경기도',
 '경남',
 '경보',
 '경북',
 '경신',
 '경영',
 '경제',
 '경제성장률',
 '계기',
 '계속',
 '계좌',
 '고',
 '고객',
 '고깃집',
 '고용',
 '고통지수',
 '곡성군',
 '곤두박질',
 '골목',
 '곳',
 '곳곳',
 '공단',
 '공인',
 '공장',
 '과',
 '과거',
 '관계자',
 '관광',
 '관련',
 '관리',
 '광주',
 '광주시',
 '교량',
 '교수',
 '교통체증',
 '구',
 '구조해',
 '국',
 '국가',
 '국내',
 '국집',
 '군',
 '권',
 '귀가',
 '규모',
 '규제',
 '그',
 '그냥',
 '근거',
 '근로자',
 '근무',
 '금고',
 '금도',
 '금리',
 '금융기관',
 '금융위기',
 '금지',
 '급락',
 '급류',
 '기간',
 '기관',
 '기대',
 '기도',
 '기록',
 '기상청',
 '기아차',
 '기약',
 '기업',
 '기운',
 '기자',
 '기적',
 '기준',
 '기준금리',
 '기해',
 '긴급',
 '길',
 '길이',
 '김모',
 '김씨',
 '김정식',
 '김지현',
 '깜깜',
 '깡통',
 '끌',
 '끝내',
 '나',
 '나루',
 '낙관',
 '날',
 '남부',
 '남북',
 '남서쪽',
 '남양주',
 '남양주시',
 '남원',
 '남해안',
 '남혜정',
 '납품',
 '낮',
 '내',
 '내년',
 '내리막',
 '내외',
 '년',
 '노트북',
 '농경',
 '농민',
 '누가',
 '눈',
 '눈치',
 '뉴스',
 '뉴시스',
 '늘',
 '다른',
 '다시',
 '다음',
 '다행',
 '단계',
 '달',
 '달라',
 '달리기',
 '담대',
 '담보',
 '담양',
 '답례',
 '닷새',
 '당국',
 '당부',
 '대가',
 '대거',
 '대금',
 '대기',
 '대기업',
 '대로',
 '대만',
 '대본',
 '대비',
 '대상',
 '대외',
 '대중교통',
 '대책',
 '대처',
 '대청댐',
 '대출',
 '대통령',
 '대표',
 '대피',
 '대합실',
 '대해',
 '대형',
 '댐',
 '댓글',
 '더',
 '덩달아',
 '데',
 '데드라인',
 '도',
 '도나',
 '도로',
 '도무지',
 '독자',
 '돈',
 '동기',
 '동반',
 '동서로',
 '동안',
 '동원',
 '동이',
 '동쪽',
 '동참',
 '동행',
 '동향',
 '되풀이',
 '두',
 '두기',
 '둔화',
 '뒤',
 '뒤편',
 '드라이브',
 '등',
 '따이공',
 '딸',
 '때',
 '때문',
 '또',
 '라며',
 '라면',
 '량',
 '로',
 '론',
 '류종은',
 '률',
 '를',
 '린',
 '링크',
 '마감',
 '마무리',
 '마이너스',
 '마찬가지',
 '만',
 '만난',
 '만인',
 '만큼',
 '말',
 '매매',
 '매몰',
 '매번',
 '매우',
 '매장',
 '매출',
 '맥줏집',
 '맹하',
 '며',
 '면세',
 '면세점',
 '명',
 '명도',
 '명동',
 '명의',
 '몇',
 '몇몇',
 '모두',
 '모바일',
 '모습',
 '모양',
 '목소리',
 '몸',
 '못',
 '무급',
 '무단',
 '무동',
 '무엇',
 '무풍지대',
 '문',
 '문의',
 '문재인',
 '문화',
 '물',
 '물량',
 '물폭탄',
 '뭘',
 '미만',
 '민정',
 '밀리',
 '밀집',
 '및',
 '바게뜨',
 '바람',
 '바잉',
 '박현준',
 '반도체',
 '반등',
 '반짝',
 '반토막',
 '발길',
 '발달',
 '발령',
 '발생',
 '발표',
 '방',
 '방대',
 '방류',
 '방식',
 '방어선',
 '방역',
 '방지원',
 '방향',
 '밭',
 '배',
 '배달',
 '배포',
 '버티고',
 '번',
 '번의',
 '번호',
 '번화가',
 '벌써',
 '벌이',
 '범',
 '범람',
 '베트남인',
 '변기',
 '변동',
 '별로',
 '별천지',
 '병원',
 '보가',
 '보고',
 '보관',
 '보따리',
 '복',
 '본부',
 '본부장',
 '볼멘소리',
 '봉쇄',
 '부근',
 '부동산',
 '부모',
 '부부',
 '부산',
 '부속품',
 '부탁',
 '부품',
 '북구',
 '북부',
 '북상',
 '북적',
 '북한',
 '분기',
 '분당구',
 '분석',
 '분위기',
 '분통',
 '불과',
 '불구',
 '불만',
 '불빛',
 '불야성',
 '불어',
 '불확실',
 '불황',
 '붕괴',
 '브랜드',
 '브레이크',
 '비',
 '비교',
 '비닐하우스',
 '비어',
 '비율',
 '비중',
 '비즈니스',
 '비행',
 '빚',
 '빚투',
 '빵',
 '뿐',
 '사',
 '사거리',
 '사고',
 '사람',
 '사리',
 '사망',
 '사망자',
 '사상',
 '사업',
 '사이',
 '사자',
 '사장',
 '사태',
 '사흘',
 '산',
 '산림청',
 '산사태',
 '산업',
 '산전수전',
 '상',
 '상공',
 '상륙',
 '상반기',
 '상인',
 '상태',
 '상품',
 '상품화',
 '상황',
 '생',
 '생각',
 '생산',
 '생중계',
 '서로',
 '서울역',
 '서쪽',
 '서해',
 '석유파동',
 '선방',
 '선회',
 '설명',
 '설상가상',
 '성남시',
 '성장',
 '세',
 '세계',
 '세면대',
 '세상',
 '셈',
 '소규모',
 '소리',
 '소방',
 '소상',
 '소셜네트워크서비스',
 '소위',
 '소진',
 '소형',
 '속',
 '속도',
 '속출',
 '손님',
 '손실',
 '손자',
 '송민섭',
 '송파',
 '수',
 '수가',
 '수단',
 '수도',
 '수도권',
 '수령',
 '수습',
 '수요',
 '수용',
 '수익',
 '수익률',
 '수준',
 '수출',
 '수치',
 '수해',
 '순환',
 '술',
 '술집',
 '숫자',
 '스루',
 '스타벅스',
 '승무원',
 '시',
 '시각',
 '시간',
 '시기',
 '시대',
 '시설',
 '시속',
 '시신',
 '시작',
 '시장',
 '시행',
 '식당',
 '식사',
 '식품위생',
 '신고',
 '신부',
 '신씨',
 '신용',
 '신용거래',
 '신용등급',
 '신종',
 '신준하',
 '신차',
 '실',
 '실감',
 '실물',
 '실적',
 '실종',
 '실종자',
 '심각',
 '쌍용차',
 '씨',
 '아래',
 '아버님',
 '아버지',
 '아산',
 '아산시',
 '아예',
 '악',
 '안',
 '안간힘',
 '안전',
 '안주',
 '액',
 '야산',
 '약속',
 '얘기',
 '어가',
 '어도',
 '어려움',
 '언제',
 '업계',
 '업무',
 '업종',
 '업체',
 '엎친',
 '여',
 '여력',
 '여성',
 '여주',
 '여파',
 '여행',
 '여행사',
 '역',
 '역대',
 '역시',
 '역학',
 '연간',
 '연구원',
 '연기',
 '연세대',
 '연속',
 '연합',
 '영상',
 '영서',
 '영업',
 '영평',
 '영향',
 '예',
 '예금',
 '예년',
 '예보',
 '예상',
 '예식',
 '예측',
 '오뚝이',
 '오산면',
 '오전',
 '오주환',
 '오키나와',
 '오프라인',
 '오후',
 '온',
 '온라인',
 '온종일',
 '온천',
 '올해',
 '왕숙천',
 '외국인',
 '외면',
 '외식',
 '외식산업',
 '외환위기',
 '요구',
 '요금',
 '요인',
 '요즘',
 '우량',
 '우려',
 '우리',
 '우리나라',
 '운영',
 '워낙',
 '원금',
 '원래',
 '원성',
 '원천',
 '월급',
 '월별',
 '웬',
 '위기',
 '위주',
 '유니폼',
 '유독',
 '유동성',
 '유례',
 '유리',
 '유지',
 '유통업',
 '윤태석',
 '율',
 '융자',
 '은',
 '은행',
 '은행권',
 '음료',
 '음식점',
 '음악',
 '응답',
 '의',
 '의료',
 '의존',
 '이',
 '이기',
 '이도',
 '이번',
 '이상',
 '이스타항공',
 '이야기',
 '이용',
 '이자카야',
 '이전',
 '이준희',
 '이즈',
 '이체',
 '이행',
 '이후',
 '인',
 '인건비',
 '인근',
 '인기',
 '인명',
 '인석',
 '인수합병',
 '인원',
 '인적',
 '인천',
 '일',
 '일대',
 '일보',
 '일본',
 '일부',
 '일시',
 '일쑤',
 '일자리',
 '일정',
 '일제',
 '임',
 '임박',
 '입',
 '입국',
 '입력',
 '입지',
 '자가',
 '자금',
 '자동차',
 '자릿수',
 '자원부',
 '자제',
 '작년',
 '작업',
 '잔액',
 '잠시',
 '장기',
 '장담',
 '장마',
 '장마전선',
 '장미',
 '장밋빛',
 '장비',
 '장사',
 '장수',
 '재',
 '재간',
 '재기',
 '재난',
 '재민',
 '재산',
 '저수지',
 '적금',
 '적자',
 '적지',
 '전',
 '전국',
 '전날',
 '전남',
 '전달',
 '전망',
 '전멸',
 '전북',
 '전세',
 '전월',
 '전장',
 '전체',
 '전통',
 '전화번호',
 '전후',
 '절망',
 '절반',
 '점',
 '점검',
 '점포',
 '접경',
 '정',
 '정기예금',
 '정도',
 '정리',
 '정말',
 '정복',
 '정부',
 '정상화',
 '정은경',
 '정자동',
 '정진호',
 '제',
 '제공',
 '제과점',
 '제방',
 '제외',
 '제조업체',
 '제주도',
 '제품',
 '제한',
 '젠',
 '조기',
 '조달',
 '조사',
 '조선일보',
 '조처',
 '종각역',
 '주',
 '주문',
 '주변',
 '주소',
 '주식',
 '주의',
 '주의보',
 '주인',
 '주차장',
 '주택',
 '줄',
 '줄곧',
 '줄줄이',
 '중',
 '중계',
 '중구',
 '중국',
 '중단',
 '중부지방',
 '중소기업',
 '중심',
 '중앙',
 '중이',
 '중장비',
 '증가',
 '증시',
 '지급',
 '지난',
 '지난달',
 '지난해',
 '지대',
 '지도',
 '지리산',
 '지면',
 '지방',
 '지방자치단체',
 '지속',
 '지수',
 '지역',
 '지원',
 '지인',
 '지자체',
 '직',
 '직원',
 '직접',
 '직할',
 '진흥',
 '질병',
 '집',
 '집계',
 '집중',
 '집중호우',
 '쪽',
 '찌',
 '차',
 '차고',
 '차량',
 '차례',
 '차로',
 '차주',
 '차지',
 '참석',
 '채',
 '채혜선',
 '책',
 '처음',
 '천막',
 '천안',
 '철',
 '철강',
 '철강업',
 '철근',
 '첨부',
 '첫',
 '첫날',
 '청미',
 '청북읍',
 '청와대',
 '청첩장',
 '청평면',
 '체감',
 '초비상',
 '초상',
 '총',
 '총력',
 '최고',
 '최근',
 '최대',
 '최대한',
 '최모',
 '최소',
 '최저',
 '최후',
 '추가',
 '축가',
 '축의금',
 '축하',
 '출시',
 '출장',
 '충남',
 '충북',
 '충주댐',
 '충청',
 '취식',
 '층',
 '친',
 '친구',
 '칠',
 '침수',
 '침체',
 '카페',
 '커피',
 '커피전문점',
 '컴퍼니',
 '컴퓨터',
 '코로나',
 '코로나바이러스',
 '타개',
 '타임',
 '탁',
 '탁금',
 '태풍',
 '터널',
 '테이블',
 '토로',
 '토사',
 '통계',
 '통계청',
 '통상',
 '통제',
 '통해',
 '투자',
 '투자자',
 '파리',
 '파손',
 '판가름',
 '판단',
 '판매',
 '패닉',
 '패스트푸드',
 '펜션',
 '편',
 '편차',
 '평가',
 '평균',
 '평년',
 '평소',
 '평택',
 '평택시',
 '포기',
 '포스코',
 '포인트',
 '포장',
 '포천',
 '폭',
 '폭우',
 '표정',
 '푸념',
 '풀이',
 '풀칠',
 '품',
 '프랜차이즈',
 '프렌',
 '프리미엄',
 '피해',
 '필리핀',
 '필요',
 '하객',
 '하구핏',
 '하늘',
 '하루',
 '하루하루',
 '하반기',
 '하소연',
 '하자',
 '하천',
 '학부',
 '한계',
 '한국',
 '한국은행',
 '한반도',
 '한숨',
 '한식',
 '한식당',
 '한탄',
 '한편',
 '항공',
 '해',
 '해도',
 '해상',
 '해석',
 '해외',
 '헤어',
 '현대',
 '현상',
 '현수',
 '현실',
 '현장',
 '현재',
 '현주소',
 '협력',
 '형강',
 '형성',
 '형태',
 '혜림',
 '호',
 '호우',
 '호우경보',
 '호텔',
 '혼주',
 '홈페이지',
 '홍',
 '홍수',
 '화',
 '화순',
 '화재',
 '확보',
 '확산',
 '확인',
 '환자',
 '활',
 '활기',
 '회',
 '회복',
 '회사',
 '회의',
 '횟집',
 '효과',
 '후',
 '후퇴',
 '훈',
 '휴가',
 '휴직',
 '흑자',
 '희망고문',
 '희비']

In [17]:
count = []
for i in txt:
    count.append([])
    for j in word_list:
        count[-1].append(i.count(j))

In [19]:
df_tf = pd.DataFrame(count, columns=word_list)
df_tf

,가건물,가게,가계,가공,가구,가까이,가동,가량,가빈,가운데,...,횟집,효과,후,후퇴,훈,휴가,휴직,흑자,희망고문,희비
0,0,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,1,0,2,0,0,0,0,0,0,0
2,0,1,0,0,0,0,0,0,0,0,...,0,0,3,0,0,0,0,0,0,0
3,0,1,0,0,0,0,0,0,0,0,...,0,0,3,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
61,0,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
62,0,0,3,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
63,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
64,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
65,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

## IDF (특정 단어 t가 등장하는 문서의 수의 역수)

In [20]:
import numpy as np

In [21]:
D = len(df_tf) # 총 문서의 수
D

66

In [22]:
df_tf.astype(bool)

,가건물,가게,가계,가공,가구,가까이,가동,가량,가빈,가운데,...,횟집,효과,후,후퇴,훈,휴가,휴직,흑자,희망고문,희비
0,False,False,False,False,False,False,False,False,False,False,...,False,False,True,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,True,False,True,False,False,False,False,False,False,False
2,False,True,False,False,False,False,False,False,False,False,...,False,False,True,False,False,False,False,False,False,False
3,False,True,False,False,False,False,False,False,False,False,...,False,False,True,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,True,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
61,False,False,False,False,False,False,False,False,False,False,...,False,False,True,False,False,False,False,False,False,False
62,False,False,True,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
63,False,False,False,False,False,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
64,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,True,False,False,False,False,False
65,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [23]:
df_tf.astype(bool).sum(axis=0)

가건물     1
가게      3
가계      2
가공      1
가구      1
       ..
휴가      1
휴직      1
흑자      1
희망고문    1
희비      1
Length: 979, dtype: int64

In [24]:
df = df_tf.astype(bool).sum(axis=0)
idf = np.log(D / (df+1))

In [25]:
idf

가건물     3.496508
가게      2.803360
가계      3.091042
가공      3.496508
가구      3.496508
          ...
휴가      3.496508
휴직      3.496508
흑자      3.496508
희망고문    3.496508
희비      3.496508
Length: 979, dtype: float64

In [26]:
df_tfidf = df_tf * idf

In [27]:
df_tfidf

,가건물,가게,가계,가공,가구,가까이,가동,가량,가빈,가운데,...,횟집,효과,후,후퇴,훈,휴가,휴직,흑자,희망고문,희비
0,0.0,0.00000,0.000000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,...,0.000000,0.0,1.054161,0.0,0.000000,0.0,0.0,0.0,0.0,0.0
1,0.0,0.00000,0.000000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,...,3.496508,0.0,2.108321,0.0,0.000000,0.0,0.0,0.0,0.0,0.0
2,0.0,2.80336,0.000000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,...,0.000000,0.0,3.162482,0.0,0.000000,0.0,0.0,0.0,0.0,0.0
3,0.0,2.80336,0.000000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,...,0.000000,0.0,3.162482,0.0,0.000000,0.0,0.0,0.0,0.0,0.0
4,0.0,0.00000,0.000000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,...,0.000000,0.0,1.054161,0.0,0.000000,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
61,0.0,0.00000,0.000000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,...,0.000000,0.0,1.054161,0.0,0.000000,0.0,0.0,0.0,0.0,0.0
62,0.0,0.00000,9.273127,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,...,0.000000,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0
63,0.0,0.00000,0.000000,0.0,0.0,3.091042,0.0,0.0,0.0,0.0,...,0.000000,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0
64,0.0,0.00000,0.000000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,...,0.000000,0.0,0.000000,0.0,3.496508,0.0,0.0,0.0,0.0,0.0
65,0.0,0.00000,0.000000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,...,0.000000,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0

## SKlearn
### 1.TF

In [28]:
from sklearn.feature_extraction.text import CountVectorizer

In [29]:
txt[0]

'수도권 대상 거리 두기 단계 시행 음식점 등 오후 대거 문 때문'

In [30]:
cv = CountVectorizer()
tdm = cv.fit_transform(txt)

In [31]:
tdm

<66x852 sparse matrix of type '<class 'numpy.int64'>'
	with 1433 stored elements in Compressed Sparse Row format>

In [32]:
tdm.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 1, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [33]:
tdm.shape

(66, 852)

In [34]:
feature = cv.get_feature_names_out()
feature

array(['가건물', '가게', '가계', '가공', '가구', '가까이', '가동', '가량', '가빈', '가운데',
       '가의', '가장', '가족', '가중', '가평', '가평군', '가평읍', '각별', '각종', '간판', '갈등',
       '갈리', '감당', '감소', '감염증', '감치', '강물', '강수', '강수량', '강원', '강원영동',
       '강제', '강타', '강풍', '강화', '개선', '개월', '개인', '거란', '거래', '거리', '거창',
       '걱정', '건물', '건설', '건의', '게릴라', '격리', '격상', '결과', '결혼식', '경기',
       '경기도', '경남', '경보', '경북', '경신', '경영', '경제', '경제성장률', '계기', '계속',
       '계좌', '고객', '고깃집', '고용', '고통지수', '곡성군', '곤두박질', '골목', '곳곳', '공단',
       '공인', '공장', '과거', '관계자', '관광', '관련', '관리', '광주', '광주시', '교량', '교수',
       '교통체증', '구조해', '국가', '국내', '국집', '귀가', '규모', '규제', '그냥', '근거',
       '근로자', '근무', '금고', '금도', '금리', '금융기관', '금융위기', '금지', '급락', '급류',
       '기간', '기관', '기대', '기도', '기록', '기상청', '기아차', '기약', '기업', '기운', '기자',
       '기적', '기준', '기준금리', '기해', '긴급', '길이', '김모', '김씨', '김정식', '김지현',
       '깜깜', '깡통', '끝내', '나루', '낙관', '남부', '남북', '남서쪽', '남양주', '남양주시',
       '남원', '남해안', '남혜정', '납품', '내년', '내리막', '내외', '노트북', '농경', '농민',
       '누가', '눈치', '뉴스', '뉴시스', '다른', '다시', '다음', '다행', '단계', '달라', '달리기',
       '담대', '담보', '담양', '답례', '닷새', '당국', '당부', '대가', '대거', '대금', '대기',
       '대기업', '대로', '대만', '대본', '대비', '대상', '대외', '대중교통', '대책', '대처',
       '대청댐', '대출', '대통령', '대표', '대피', '대합실', '대해', '대형', '댓글', '덩달아',
       '데드라인', '도나', '도로', '도무지', '독자', '동기', '동반', '동서로', '동안', '동원',
       '동이', '동쪽', '동참', '동행', '동향', '되풀이', '두기', '둔화', '뒤편', '드라이브',
       '따이공', '때문', '라며', '라면', '류종은', '링크', '마감', '마무리', '마이너스', '마찬가지',
       '만난', '만인', '만큼', '매매', '매몰', '매번', '매우', '매장', '매출', '맥줏집', '맹하',
       '면세', '면세점', '명도', '명동', '명의', '몇몇', '모두', '모바일', '모습', '모양',
       '목소리', '무급', '무단', '무동', '무엇', '무풍지대', '문의', '문재인', '문화', '물량',
       '물폭탄', '미만', '민정', '밀리', '밀집', '바게뜨', '바람', '바잉', '박현준', '반도체',
       '반등', '반짝', '반토막', '발길', '발달', '발령', '발생', '발표', '방대', '방류', '방식',
       '방어선', '방역', '방지원', '방향', '배달', '배포', '버티고', '번의', '번호', '번화가',
       '벌써', '벌이', '범람', '베트남인', '변기', '변동', '별로', '별천지', '병원', '보가',
       '보고', '보관', '보따리', '본부', '본부장', '볼멘소리', '봉쇄', '부근', '부동산', '부모',
       '부부', '부산', '부속품', '부탁', '부품', '북구', '북부', '북상', '북적', '북한', '분기',
       '분당구', '분석', '분위기', '분통', '불과', '불구', '불만', '불빛', '불야성', '불어',
       '불확실', '불황', '붕괴', '브랜드', '브레이크', '비교', '비닐하우스', '비어', '비율', '비중',
       '비즈니스', '비행', '빚투', '사거리', '사고', '사람', '사리', '사망', '사망자', '사상',
       '사업', '사이', '사자', '사장', '사태', '사흘', '산림청', '산사태', '산업', '산전수전',
       '상공', '상륙', '상반기', '상인', '상태', '상품', '상품화', '상황', '생각', '생산',
       '생중계', '서로', '서울역', '서쪽', '서해', '석유파동', '선방', '선회', '설명', '설상가상',
       '성남시', '성장', '세계', '세면대', '세상', '소규모', '소리', '소방', '소상',
       '소셜네트워크서비스', '소위', '소진', '소형', '속도', '속출', '손님', '손실', '손자', '송민섭',
       '송파', '수가', '수단', '수도', '수도권', '수령', '수습', '수요', '수용', '수익', '수익률',
       '수준', '수출', '수치', '수해', '순환', '술집', '숫자', '스루', '스타벅스', '승무원',
       '시각', '시간', '시기', '시대', '시설', '시속', '시신', '시작', '시장', '시행', '식당',
       '식사', '식품위생', '신고', '신부', '신씨', '신용', '신용거래', '신용등급', '신종', '신준하',
       '신차', '실감', '실물', '실적', '실종', '실종자', '심각', '쌍용차', '아래', '아버님',
       '아버지', '아산', '아산시', '아예', '안간힘', '안전', '안주', '야산', '약속', '얘기',
       '어가', '어도', '어려움', '언제', '업계', '업무', '업종', '업체', '엎친', '여력', '여성',
       '여주', '여파', '여행', '여행사', '역대', '역시', '역학', '연간', '연구원', '연기',
       '연세대', '연속', '연합', '영상', '영서', '영업', '영평', '영향', '예금', '예년', '예보',
       '예상', '예식', '예측', '오뚝이', '오산면', '오전', '오주환', '오키나와', '오프라인', '오후',
       '온라인', '온종일', '온천', '올해', '왕숙천', '외국인', '외면', '외식', '외식산업', '외환위기',
       '요구', '요금', '요인', '요즘', '우량', '우려', '우리', '우리나라', '운영', '워낙', '원금',
       '원래', '원성', '원천', '월급', '월별', '위기', '위주', '유니폼', '유독', '유동성', '유례',
       '유리', '유지', '유통업', '윤태석', '융자', '은행', '은행권', '음료', '음식점', '음악',
       '응답', '의료', '의존', '이기', '이도', '이번', '이상', '이스타항공', '이야기', '이용',
       '이자카야', '이전', '이준희', '이즈', '이체', '이행', '이후', '인건비', '인근', '인기',
       '인명', '인석', '인수합병', '인원', '인적', '인천', '일대', '일보', '일본', '일부', '일시',
       '일쑤', '일자리', '일정', '일제', '임박', '입국', '입력', '입지', '자가', '자금', '자동차',
       '자릿수', '자원부', '자제', '작년', '작업', '잔액', '잠시', '장기', '장담', '장마',
       '장마전선', '장미', '장밋빛', '장비', '장사', '장수', '재간', '재기', '재난', '재민',
       '재산', '저수지', '적금', '적자', '적지', '전국', '전날', '전남', '전달', '전망', '전멸',
       '전북', '전세', '전월', '전장', '전체', '전통', '전화번호', '전후', '절망', '절반', '점검',
       '점포', '접경', '정기예금', '정도', '정리', '정말', '정복', '정부', '정상화', '정은경',
       '정자동', '정진호', '제공', '제과점', '제방', '제외', '제조업체', '제주도', '제품', '제한',
       '조기', '조달', '조사', '조선일보', '조처', '종각역', '주문', '주변', '주소', '주식',
       '주의', '주의보', '주인', '주차장', '주택', '줄곧', '줄줄이', '중계', '중구', '중국',
       '중단', '중부지방', '중소기업', '중심', '중앙', '중이', '중장비', '증가', '증시', '지급',
       '지난', '지난달', '지난해', '지대', '지도', '지리산', '지면', '지방', '지방자치단체', '지속',
       '지수', '지역', '지원', '지인', '지자체', '직원', '직접', '직할', '진흥', '질병', '집계',
       '집중', '집중호우', '차고', '차량', '차례', '차로', '차주', '차지', '참석', '채혜선',
       '처음', '천막', '천안', '철강', '철강업', '철근', '첨부', '첫날', '청미', '청북읍',
       '청와대', '청첩장', '청평면', '체감', '초비상', '초상', '총력', '최고', '최근', '최대',
       '최대한', '최모', '최소', '최저', '최후', '추가', '축가', '축의금', '축하', '출시', '출장',
       '충남', '충북', '충주댐', '충청', '취식', '친구', '침수', '침체', '카페', '커피',
       '커피전문점', '컴퍼니', '컴퓨터', '코로나', '코로나바이러스', '타개', '타임', '탁금', '태풍',
       '터널', '테이블', '토로', '토사', '통계', '통계청', '통상', '통제', '통해', '투자',
       '투자자', '파리', '파손', '판가름', '판단', '판매', '패닉', '패스트푸드', '펜션', '편차',
       '평가', '평균', '평년', '평소', '평택', '평택시', '포기', '포스코', '포인트', '포장',
       '포천', '폭우', '표정', '푸념', '풀이', '풀칠', '프랜차이즈', '프렌', '프리미엄', '피해',
       '필리핀', '필요', '하객', '하구핏', '하늘', '하루', '하루하루', '하반기', '하소연', '하자',
       '하천', '학부', '한계', '한국', '한국은행', '한반도', '한숨', '한식', '한식당', '한탄',
       '한편', '항공', '해도', '해상', '해석', '해외', '헤어', '현대', '현상', '현수', '현실',
       '현장', '현재', '현주소', '협력', '형강', '형성', '형태', '혜림', '호우', '호우경보',
       '호텔', '혼주', '홈페이지', '홍수', '화순', '화재', '확보', '확산', '확인', '환자', '활기',
       '회복', '회사', '회의', '횟집', '효과', '후퇴', '휴가', '휴직', '흑자', '희망고문', '희비'],
      dtype=object)

In [35]:
tf_ = pd.DataFrame(tdm.toarray(), columns=feature)
tf_

,가건물,가게,가계,가공,가구,가까이,가동,가량,가빈,가운데,...,회사,회의,횟집,효과,후퇴,휴가,휴직,흑자,희망고문,희비
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
2,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
61,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
62,0,0,3,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
63,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
64,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
65,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

### 2.TF_IDF|

In [36]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [38]:
txt[0]

'수도권 대상 거리 두기 단계 시행 음식점 등 오후 대거 문 때문'

In [39]:
tfidf_vectorizer = TfidfVectorizer()
tfidf_matrix = tfidf_vectorizer.fit_transform(txt)

In [41]:
tfidf_matrix

<66x852 sparse matrix of type '<class 'numpy.float64'>'
	with 1433 stored elements in Compressed Sparse Row format>

In [42]:
tfidf_matrix.toarray()

array([[0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.17370431, 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])

In [43]:
tfidf_feature = tfidf_vectorizer.get_feature_names_out()

In [44]:
tfidf_feature

array(['가건물', '가게', '가계', '가공', '가구', '가까이', '가동', '가량', '가빈', '가운데',
       '가의', '가장', '가족', '가중', '가평', '가평군', '가평읍', '각별', '각종', '간판', '갈등',
       '갈리', '감당', '감소', '감염증', '감치', '강물', '강수', '강수량', '강원', '강원영동',
       '강제', '강타', '강풍', '강화', '개선', '개월', '개인', '거란', '거래', '거리', '거창',
       '걱정', '건물', '건설', '건의', '게릴라', '격리', '격상', '결과', '결혼식', '경기',
       '경기도', '경남', '경보', '경북', '경신', '경영', '경제', '경제성장률', '계기', '계속',
       '계좌', '고객', '고깃집', '고용', '고통지수', '곡성군', '곤두박질', '골목', '곳곳', '공단',
       '공인', '공장', '과거', '관계자', '관광', '관련', '관리', '광주', '광주시', '교량', '교수',
       '교통체증', '구조해', '국가', '국내', '국집', '귀가', '규모', '규제', '그냥', '근거',
       '근로자', '근무', '금고', '금도', '금리', '금융기관', '금융위기', '금지', '급락', '급류',
       '기간', '기관', '기대', '기도', '기록', '기상청', '기아차', '기약', '기업', '기운', '기자',
       '기적', '기준', '기준금리', '기해', '긴급', '길이', '김모', '김씨', '김정식', '김지현',
       '깜깜', '깡통', '끝내', '나루', '낙관', '남부', '남북', '남서쪽', '남양주', '남양주시',
       '남원', '남해안', '남혜정', '납품', '내년', '내리막', '내외', '노트북', '농경', '농민',
       '누가', '눈치', '뉴스', '뉴시스', '다른', '다시', '다음', '다행', '단계', '달라', '달리기',
       '담대', '담보', '담양', '답례', '닷새', '당국', '당부', '대가', '대거', '대금', '대기',
       '대기업', '대로', '대만', '대본', '대비', '대상', '대외', '대중교통', '대책', '대처',
       '대청댐', '대출', '대통령', '대표', '대피', '대합실', '대해', '대형', '댓글', '덩달아',
       '데드라인', '도나', '도로', '도무지', '독자', '동기', '동반', '동서로', '동안', '동원',
       '동이', '동쪽', '동참', '동행', '동향', '되풀이', '두기', '둔화', '뒤편', '드라이브',
       '따이공', '때문', '라며', '라면', '류종은', '링크', '마감', '마무리', '마이너스', '마찬가지',
       '만난', '만인', '만큼', '매매', '매몰', '매번', '매우', '매장', '매출', '맥줏집', '맹하',
       '면세', '면세점', '명도', '명동', '명의', '몇몇', '모두', '모바일', '모습', '모양',
       '목소리', '무급', '무단', '무동', '무엇', '무풍지대', '문의', '문재인', '문화', '물량',
       '물폭탄', '미만', '민정', '밀리', '밀집', '바게뜨', '바람', '바잉', '박현준', '반도체',
       '반등', '반짝', '반토막', '발길', '발달', '발령', '발생', '발표', '방대', '방류', '방식',
       '방어선', '방역', '방지원', '방향', '배달', '배포', '버티고', '번의', '번호', '번화가',
       '벌써', '벌이', '범람', '베트남인', '변기', '변동', '별로', '별천지', '병원', '보가',
       '보고', '보관', '보따리', '본부', '본부장', '볼멘소리', '봉쇄', '부근', '부동산', '부모',
       '부부', '부산', '부속품', '부탁', '부품', '북구', '북부', '북상', '북적', '북한', '분기',
       '분당구', '분석', '분위기', '분통', '불과', '불구', '불만', '불빛', '불야성', '불어',
       '불확실', '불황', '붕괴', '브랜드', '브레이크', '비교', '비닐하우스', '비어', '비율', '비중',
       '비즈니스', '비행', '빚투', '사거리', '사고', '사람', '사리', '사망', '사망자', '사상',
       '사업', '사이', '사자', '사장', '사태', '사흘', '산림청', '산사태', '산업', '산전수전',
       '상공', '상륙', '상반기', '상인', '상태', '상품', '상품화', '상황', '생각', '생산',
       '생중계', '서로', '서울역', '서쪽', '서해', '석유파동', '선방', '선회', '설명', '설상가상',
       '성남시', '성장', '세계', '세면대', '세상', '소규모', '소리', '소방', '소상',
       '소셜네트워크서비스', '소위', '소진', '소형', '속도', '속출', '손님', '손실', '손자', '송민섭',
       '송파', '수가', '수단', '수도', '수도권', '수령', '수습', '수요', '수용', '수익', '수익률',
       '수준', '수출', '수치', '수해', '순환', '술집', '숫자', '스루', '스타벅스', '승무원',
       '시각', '시간', '시기', '시대', '시설', '시속', '시신', '시작', '시장', '시행', '식당',
       '식사', '식품위생', '신고', '신부', '신씨', '신용', '신용거래', '신용등급', '신종', '신준하',
       '신차', '실감', '실물', '실적', '실종', '실종자', '심각', '쌍용차', '아래', '아버님',
       '아버지', '아산', '아산시', '아예', '안간힘', '안전', '안주', '야산', '약속', '얘기',
       '어가', '어도', '어려움', '언제', '업계', '업무', '업종', '업체', '엎친', '여력', '여성',
       '여주', '여파', '여행', '여행사', '역대', '역시', '역학', '연간', '연구원', '연기',
       '연세대', '연속', '연합', '영상', '영서', '영업', '영평', '영향', '예금', '예년', '예보',
       '예상', '예식', '예측', '오뚝이', '오산면', '오전', '오주환', '오키나와', '오프라인', '오후',
       '온라인', '온종일', '온천', '올해', '왕숙천', '외국인', '외면', '외식', '외식산업', '외환위기',
       '요구', '요금', '요인', '요즘', '우량', '우려', '우리', '우리나라', '운영', '워낙', '원금',
       '원래', '원성', '원천', '월급', '월별', '위기', '위주', '유니폼', '유독', '유동성', '유례',
       '유리', '유지', '유통업', '윤태석', '융자', '은행', '은행권', '음료', '음식점', '음악',
       '응답', '의료', '의존', '이기', '이도', '이번', '이상', '이스타항공', '이야기', '이용',
       '이자카야', '이전', '이준희', '이즈', '이체', '이행', '이후', '인건비', '인근', '인기',
       '인명', '인석', '인수합병', '인원', '인적', '인천', '일대', '일보', '일본', '일부', '일시',
       '일쑤', '일자리', '일정', '일제', '임박', '입국', '입력', '입지', '자가', '자금', '자동차',
       '자릿수', '자원부', '자제', '작년', '작업', '잔액', '잠시', '장기', '장담', '장마',
       '장마전선', '장미', '장밋빛', '장비', '장사', '장수', '재간', '재기', '재난', '재민',
       '재산', '저수지', '적금', '적자', '적지', '전국', '전날', '전남', '전달', '전망', '전멸',
       '전북', '전세', '전월', '전장', '전체', '전통', '전화번호', '전후', '절망', '절반', '점검',
       '점포', '접경', '정기예금', '정도', '정리', '정말', '정복', '정부', '정상화', '정은경',
       '정자동', '정진호', '제공', '제과점', '제방', '제외', '제조업체', '제주도', '제품', '제한',
       '조기', '조달', '조사', '조선일보', '조처', '종각역', '주문', '주변', '주소', '주식',
       '주의', '주의보', '주인', '주차장', '주택', '줄곧', '줄줄이', '중계', '중구', '중국',
       '중단', '중부지방', '중소기업', '중심', '중앙', '중이', '중장비', '증가', '증시', '지급',
       '지난', '지난달', '지난해', '지대', '지도', '지리산', '지면', '지방', '지방자치단체', '지속',
       '지수', '지역', '지원', '지인', '지자체', '직원', '직접', '직할', '진흥', '질병', '집계',
       '집중', '집중호우', '차고', '차량', '차례', '차로', '차주', '차지', '참석', '채혜선',
       '처음', '천막', '천안', '철강', '철강업', '철근', '첨부', '첫날', '청미', '청북읍',
       '청와대', '청첩장', '청평면', '체감', '초비상', '초상', '총력', '최고', '최근', '최대',
       '최대한', '최모', '최소', '최저', '최후', '추가', '축가', '축의금', '축하', '출시', '출장',
       '충남', '충북', '충주댐', '충청', '취식', '친구', '침수', '침체', '카페', '커피',
       '커피전문점', '컴퍼니', '컴퓨터', '코로나', '코로나바이러스', '타개', '타임', '탁금', '태풍',
       '터널', '테이블', '토로', '토사', '통계', '통계청', '통상', '통제', '통해', '투자',
       '투자자', '파리', '파손', '판가름', '판단', '판매', '패닉', '패스트푸드', '펜션', '편차',
       '평가', '평균', '평년', '평소', '평택', '평택시', '포기', '포스코', '포인트', '포장',
       '포천', '폭우', '표정', '푸념', '풀이', '풀칠', '프랜차이즈', '프렌', '프리미엄', '피해',
       '필리핀', '필요', '하객', '하구핏', '하늘', '하루', '하루하루', '하반기', '하소연', '하자',
       '하천', '학부', '한계', '한국', '한국은행', '한반도', '한숨', '한식', '한식당', '한탄',
       '한편', '항공', '해도', '해상', '해석', '해외', '헤어', '현대', '현상', '현수', '현실',
       '현장', '현재', '현주소', '협력', '형강', '형성', '형태', '혜림', '호우', '호우경보',
       '호텔', '혼주', '홈페이지', '홍수', '화순', '화재', '확보', '확산', '확인', '환자', '활기',
       '회복', '회사', '회의', '횟집', '효과', '후퇴', '휴가', '휴직', '흑자', '희망고문', '희비'],
      dtype=object)

In [45]:
tfidf_ = pd.DataFrame(tfidf_matrix.toarray(), columns=tfidf_feature)

In [46]:
tfidf_

,가건물,가게,가계,가공,가구,가까이,가동,가량,가빈,가운데,...,회사,회의,횟집,효과,후퇴,휴가,휴직,흑자,희망고문,희비
0,0.0,0.000000,0.000000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,...,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.000000,0.000000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,...,0.0,0.0,0.159872,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.173704,0.000000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,...,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.122296,0.000000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,...,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.000000,0.000000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,...,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
61,0.0,0.000000,0.000000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,...,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
62,0.0,0.000000,0.449992,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,...,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
63,0.0,0.000000,0.000000,0.0,0.0,0.195778,0.0,0.0,0.0,0.0,...,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
64,0.0,0.000000,0.000000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,...,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
65,0.0,0.000000,0.000000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,...,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [47]:
df_tfidf

,가건물,가게,가계,가공,가구,가까이,가동,가량,가빈,가운데,...,횟집,효과,후,후퇴,훈,휴가,휴직,흑자,희망고문,희비
0,0.0,0.00000,0.000000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,...,0.000000,0.0,1.054161,0.0,0.000000,0.0,0.0,0.0,0.0,0.0
1,0.0,0.00000,0.000000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,...,3.496508,0.0,2.108321,0.0,0.000000,0.0,0.0,0.0,0.0,0.0
2,0.0,2.80336,0.000000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,...,0.000000,0.0,3.162482,0.0,0.000000,0.0,0.0,0.0,0.0,0.0
3,0.0,2.80336,0.000000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,...,0.000000,0.0,3.162482,0.0,0.000000,0.0,0.0,0.0,0.0,0.0
4,0.0,0.00000,0.000000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,...,0.000000,0.0,1.054161,0.0,0.000000,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
61,0.0,0.00000,0.000000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,...,0.000000,0.0,1.054161,0.0,0.000000,0.0,0.0,0.0,0.0,0.0
62,0.0,0.00000,9.273127,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,...,0.000000,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0
63,0.0,0.00000,0.000000,0.0,0.0,3.091042,0.0,0.0,0.0,0.0,...,0.000000,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0
64,0.0,0.00000,0.000000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,...,0.000000,0.0,0.000000,0.0,3.496508,0.0,0.0,0.0,0.0,0.0
65,0.0,0.00000,0.000000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,...,0.000000,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0