In [1]:
import myweather as wt

In [2]:
dir(wt)

['__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 'connect',
 'find_code',
 'get_weather',
 'json',
 'pd',
 'requests',
 'time']

In [4]:
dt = wt.get_weather(20220101, 20220110, '속초')
display(dt)

  stnId          tm avgTa minTa maxTa sumRn maxWs avgWs
0    90  2022-01-01  -3.3  -9.2   2.1         2.6   1.3
1    90  2022-01-02   2.2  -2.4   5.9         5.4   2.1
2    90  2022-01-03   0.6  -3.0   3.0         4.7   2.1
3    90  2022-01-04  -1.2  -4.2   1.8         5.6   2.1
4    90  2022-01-05  -1.5  -4.9   1.9         3.7   1.9
5    90  2022-01-06  -1.2  -4.7   3.3         6.6   2.2
6    90  2022-01-07  -0.4  -4.2   3.9         2.5   1.5
7    90  2022-01-08   3.3  -2.4   5.4         4.7   2.1
8    90  2022-01-09   1.9  -1.2   5.2         4.4   1.9
9    90  2022-01-10   1.8  -2.0   5.1         3.8   1.7